---
- hosts: onos_control
  remote_user: ubuntu
  become: yes
  var:
    onos_version: 1.11.1
  tasks:
    - name: Install basic packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - gtar
        - unzip

    - name: Purge OpenJDK installed
      apt:
        name: "openjdk*"
        state: absent

    - name: Install software-properties-common packages
      apt:
        name: software-properties-common
        state: present
        update_cache: yes

    - name: Add JAVA APT Repository
      apt_repository:
        repo: 'ppa:webupd8team/java'
        state: present

    - name: Add an APT signing key for JAVA from Ubuntu server
      apt_key:
        id: EEA14886
        url: 'hkp://keyserver.ubuntu.com:80'
        state: present

    - name: Install JAVA packages
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_itmes:
        - oracle-java8-installer
        - oracle-java8-set-default

    - name: Create opt directory
      file:
        path: /opt
        state: directory
        owner: root
        group: root
        mode: 0755
        recurse: yes

    - name: Download ONOS
      get_url:
        url: http://downloads.onosproject.org/release/onos-"{{onos_version}}".tar.gz
        dest: /root/onos.tar.gz

    - name: Extract ONOS
      unarchive:
        src: /root/onos.tar.gz
        dest: /opt/onos/
        remote_src: yes

    - name: Execute ONOS
      command: screen -dmS odl_control && screen -S odl_control -X stuff $"/opt/onos/bin/onos-service start"
