# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

IS_SWARM=<IS_SWARM>
CLUSTER_NUMBERS=<CLUSTER_NUMBERS>
CONTROL_NUMBERS=<CONTROL_NUMBERS>
CLIENT_NUMBERS=<CLIENT_NUMBERS>
TEST_TITLE="nettest"

CONTROL_CPU="1"
CONTROL_RAM="1024"
CLIENT_CPU="1"
CLIENT_RAM="1024"
 
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.provision :shell, path: "init.sh"

    (1..CLUSTER_NUMBERS).each do |k|
        (1..CONTROL_NUMBERS).each do |i|
            config.vm.define "#{TEST_TITLE}-control#{k}-#{i}" do |ctrl|
                ctrl.vm.hostname = "#{TEST_TITLE}-control#{k}-#{i}"
                ctrl.vm.network "private_network", ip: "192.168.12#{k}.10#{i}"
                ctrl.vm.network "private_network", ip: "192.168.13#{k}.10#{i}"
                ctrl.vm.provider "virtualbox" do |v|
                    v.name = "#{TEST_TITLE}-control#{k}-#{i}"
                    v.memory = CONTROL_RAM
                    v.cpus = CONTROL_CPU
                end

                if IS_SWARM == 1
                    if i == 1
                        ctrl.vm.provision :shell, inline: "docker swarm init --advertise-addr=192.168.12#{k}.10#{i}"
                        ctrl.vm.provision :shell, inline: "docker swarm join-token manager | grep docker > /vagrant/join#{k}.mng"
                        ctrl.vm.provision :shell, inline: "docker swarm join-token worker | grep docker > /vagrant/join#{k}.wkr"
                    else
                        ctrl.vm.provision :shell, inline: "bash /vagrant/join#{k}.mng"
                        if i == CONTROL_NUMBERS
                            ctrl.vm.provision :shell, inline: "rm /vagrant/join#{k}.mng"
                        end            
                    end
                end
            end
        end

        (1..CLIENT_NUMBERS).each do |j|
            config.vm.define "#{TEST_TITLE}-client#{k}-#{j}" do |cli|
                client_ip_suffix = CONTROL_NUMBERS + j
                cli.vm.hostname = "#{TEST_TITLE}-client#{k}-#{j}"
                cli.vm.network "private_network", ip: "192.168.12#{k}.10#{client_ip_suffix}"
                cli.vm.network "private_network", ip: "192.168.13#{k}.10#{client_ip_suffix}"
                cli.vm.provider "virtualbox" do |v|
                    v.name = "#{TEST_TITLE}-client#{k}-#{j}"
                    v.memory = CLIENT_RAM
                    v.cpus = CLIENT_CPU
                end

                if IS_SWARM == 1
                    cli.vm.provision :shell, inline: "bash /vagrant/join#{k}.wkr"
                    if j == CLIENT_NUMBERS
                        cli.vm.provision :shell, inline: "rm /vagrant/join#{k}.wkr"
                    end
                end
            end
        end
    end
end

