# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
EXIST_ANSIBLE=1
BOX_NUMBERS=1
TEST_TITLE="ansible"

ANSIBLE_CPU="2"
ANSIBLE_RAM="2048"
BOX_CPU="1"
BOX_RAM="1024"
 
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    if EXIST_ANSIBLE == 1
        config.vm.define "ansible-control" do |ob|
            ob.vm.hostname = "ansible-control"
            ob.vm.network "private_network", ip: "192.168.115.100"
            ob.vm.provider "virtualbox" do |v|
                v.name = "ansible-control"
                v.cpus = ANSIBLE_CPU
                v.memory = ANSIBLE_RAM
            end
            ob.vm.provision :shell, path: "init_ansible.sh", privileged: false
        end
    end

    (1..BOX_NUMBERS).each do |i|
        config.vm.define "#{TEST_TITLE}-box#{i}" do |ctrl|
            ctrl.vm.hostname = "#{TEST_TITLE}-box#{i}"
            ctrl.vm.network "private_network", ip: "192.168.115.10#{i}"
            ctrl.vm.provider "virtualbox" do |v|
                v.name = "#{TEST_TITLE}-box#{i}"
                v.cpus = BOX_CPU
                v.memory = BOX_RAM
            end
            ctrl.vm.provision :shell, path: "init_box.sh"
            if EXIST_ANSIBLE==1
               ctrl.vm.provision :shell, inline: "cat /vagrant/post_key.pub >> ${HOME}/.ssh/authorized_keys", privileged: false
            end
        end
    end
end
